# -*- coding: utf-8 -*-
"""Mini_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19EcCUrhNJEljhg6sY6aqipQf1qMDaElz
"""

#easiest but lenthy
print("================Mini Calculator================")
while True:

  print("================MENU================")
  print("1. Addition ")
  print("2. Subtraction ")
  print("3. Multiplication ")
  print("4. Division ")
  print("5. Exit ")
  choice = input("Enter your choice: ")
  if choice == "1":
     while True:
        try:
           num1 = float(input("Enter first number: "))
           num2 = float(input("Enter second number: "))
           result = num1 + num2
           print("The sum of " + str(num1) +" and "+ str(num2) + " is " + str(result))
           break
        except ValueError:
            print("Invalid input. Please enter a number.")
  elif choice == "2":
        while True:
          try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
            result = num1 - num2
            print("The difference between "+  str(num1) + " and " + str(num2) + " is " + str(result))
            break
          except ValueError:
            print("Invalid input. Please enter a number.")
  elif choice == "3":
        while True:
            try:
             num1 = float(input("Enter first number: "))
             num2 = float(input("Enter second number: "))
             result = num1 * num2
             print("The product of " + str(num1) + " and " + str(num2) + " is " + str(result))
             break
            except ValueError:
             print("Invalid input. Please enter a number.")
  elif choice == "4":
        while True:
         try:
          num1 = float(input("Enter first number: "))

          num2 = float(input("Enter second number: "))

          result = num1 / num2
          print("The quotient of " + str(num1) + " and " + str(num2) + " is " + str(result))
          break
         except ValueError:
            print("Invalid input. Please enter a number.")
         except ZeroDivisionError:
            print("Error: Division by zero is not allowed.")
  elif choice == "5":
    print("Exiting, Good Bye!! ")
    break
  else:
    print("Invalid choice. Please try again.Enter a number 1-5. ")

#using def and little shorter
print("================Mini Calculator================")

while True:
  def numbers():
     num1 = float(input("Enter first number: "))
     num2 = float(input("Enter second number: "))
     return num1, num2

  print("================MENU================")
  print("1. Addition ")
  print("2. Subtraction ")
  print("3. Multiplication ")
  print("4. Division ")
  print("5. Exit ")
  choice = input("Enter your choice: ")
  if choice == "1":
     while True:
        try:


           num1, num2 = numbers()

           result = num1 + num2
           print("The sum of " + str(num1) +" and "+ str(num2) + " is " + str(result))
           break
        except ValueError:
            print("Invalid input. Please enter a number.")
  elif choice == "2":
        while True:
          try:
            num1, num2 = numbers()
            result = num1 - num2
            print("The difference between "+  str(num1) + " and " + str(num2) + " is " + str(result))
            break
          except ValueError:
            print("Invalid input. Please enter a number.")
  elif choice == "3":
        while True:
            try:
             num1, num2 = numbers()
             result = num1 * num2
             print("The product of " + str(num1) + " and " + str(num2) + " is " + str(result))
             break
            except ValueError:
             print("Invalid input. Please enter a number.")
  elif choice == "4":
        while True:
         try:
          num1, num2 = numbers()

          result = num1 / num2
          print("The quotient of " + str(num1) + " and " + str(num2) + " is " + str(result))
          break
         except ValueError:
            print("Invalid input. Please enter a number.")
         except ZeroDivisionError:
            print("Error: Division by zero is not allowed.")
  elif choice == "5":
    print("Exiting, Good Bye!! ")
    break
  else:
    print("Invalid choice. Please try again.Enter a number 1-5. ")

#using "f" to make it more shorter
print("================Mini Calculator================")

while True:
  def numbers():
     num1 = float(input("Enter first number: "))
     num2 = float(input("Enter second number: "))
     return num1, num2

  print("================MENU================")
  print("1. Addition ")
  print("2. Subtraction ")
  print("3. Multiplication ")
  print("4. Division ")
  print("5. Exit ")
  choice = input("Enter your choice: ")
  if choice == "1":
     while True:
        try:
            num1, num2 = numbers()
            result = num1 + num2
           print(f"Sum of {num1} and {num2} is {result}")
           break
        except ValueError:
            print("Invalid input. Please enter a number.")
  elif choice == "2":
        while True:
          try:
            num1, num2 = numbers()
            result = num1 - num2
            print(f"The difference between {num1} and {num2} is {result}")
            break
          except ValueError:
            print("Invalid input. Please enter a number.")
  elif choice == "3":
        while True:
            try:
             num1, num2 = numbers()
             result = num1 * num2
             print(f"The product of {num1} and {num2} is {result}")
             break
            except ValueError:
             print("Invalid input. Please enter a number.")
  elif choice == "4":
        while True:
         try:
          num1, num2 = numbers()

          result = num1 / num2
          print(f"The quotient of {num1} and {num2} is {result}")
          break
         except ValueError:
            print("Invalid input. Please enter a number.")
         except ZeroDivisionError:
            print("Error: Division by zero is not allowed.")
  elif choice == "5":
    print("Exiting, Good Bye!! ")
    break
  else:
    print("Invalid choice. Please try again.Enter a number 1-5. ")